language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
before_install:
  - pip install -U pip
install:
  - pip install -U numpy
  - pip install -U https://github.com/theano/theano/archive/master.zip
  - pip install -U networkx
  - pip install -U six
  - pip install -U toolz
  - pip install -U lasagne
  - pip install -U scikit-image
  - pip install -U nose
  - pip install -U matplotlib
script:
  - THEANO_FLAGS=floatX=float32 nosetests -v
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
