language: python
python:
  - "2.7"
  # - "3.5"
# command to install dependencies
install:
  - pip install numpy
  - pip install https://github.com/theano/theano/archive/master.zip
  - pip install networkx
  - pip install six
  - pip install toolz
  - pip install lasagne
  - pip install scikit-image
  - pip install nose
# command to run tests
script: nosetests -v
